Add links and info about testing failure states and output filters.
galaxy-iuc/standards pull request #31
Opened 2016-07-19 16:03 UTC by jmchilton

xref https://github.com/galaxyproject/tools-iuc/pull/883 - goal is write tests to verify tools like this properly filter.

2016-07-19 16:05 UTC, peterjc commented on docs/best_practices/tool_xml.rst
> +sand should be incremented with each change of the wrapper that is
typo

2016-07-19 16:10 UTC, jmchilton commented on docs/best_practices/tool_xml.rst
> +sand should be incremented with each change of the wrapper that is
Opps - not sure how that happened. Will rebase without that.

2016-07-19 16:22 UTC, nsoranzo commented
:+1:

2017-02-15 21:55 UTC, yhoogstrate requested changes
`https://`, further approved 👍

2017-02-16 13:47 UTC, jmchilton commented
Updated to use https - thanks @yhoogstrate !

2017-02-16 14:04 UTC, yhoogstrate approved these changes

2017-02-16 15:44 UTC, merged